### ISSUE TITLE
Oxid 4.9

### ISSUE THREAD

**Issue by hoffa87** [vanilla-thunder/vt-productlists#1]
hey marat,

first of all i want to say thanks for all these nice extentions.

Is it possibile to get the module (vt-nca) ready for Oxid 4.9?
It would be fantastic if you can help me :). I try this version but it doesnt work :(

all the best
marco

**Comment by vanilla-thunder** [comment]
hey marco,
i will have a look at it today,

best regards,
marat

**Comment by hoffa87** [comment]
that would be very nice, take your time and thank you very much for the fast reply.

**Comment by vanilla-thunder** [comment]
hello marco, 
I just pushed the new module update for oxid 4.9
There is a small guide in the readme with all the parameters, but i will also add a larger manual in the next days.
If you have questions, feel free to contact me.

cheers

**Comment by hoffa87** [comment]
hey :),

WOW, thank you very much. I´ll try it at weekend and think i dont need any more manual.

All the best and a nice Weekend
Cheers!
